### ISSUE TITLE
Receiving error "The request is missing a required parameter: grant_type"

### ISSUE THREAD

**Issue by geoffjay** [FusionAuth/fusionauth-example-python-django#2]
I have quadruple checked my values for `FUSION_AUTH_API_KEY`, `FUSION_AUTH_APP_ID`, `FUSION_AUTH_CLIENT_SECRET` against the running instance of FusionAuth. The response that I get from the call to `exchange_o_auth_code_for_access_token` fails with the error `The request is missing a required parameter: grant_type` when attempting to login using either a Google account through oauth2 or with a valid Django user.

As far as I can tell, the setup in Google is valid and I'm given a login form, nothing fails, and tokens are returned. What is the way in FusionAuth to increase logging to determine where this is failing? Should there have been some kind of setup performed in FA to specify `grant_type` or does the request need to be modified in some way to include that?

**Comment by mooreds** [comment]
@geoffjay 

Ah, I think it is an issue with the ordering of the arguments to the call here: https://github.com/FusionAuth/fusionauth-example-python-django/blob/master/secretbirthdays/secretbirthdaysapp/views.py#L38

You can see that in that code, the redirect_url is before the application_id, which is also the client id.

But here: https://github.com/FusionAuth/fusionauth-python-client/blob/master/src/main/python/fusionauth/fusionauth_client.py#L775 the client id is before the redirect url. That is a change that occurred in 1.19.0: https://fusionauth.io/docs/v1/tech/release-notes/#version-1-19-0

Can you try reversing the order of the args in the sample app and see if that resolves your problem?

If so, I'll modify the example app. (I think we fixed this in the blog post but the change didn't propagate to the example app, sorry!)

**Comment by geoffjay** [comment]
I don't know how this happened but with v1.21.0 the function `exchange_o_auth_code_for_access_token` was:
```python
return self.start_anonymous().uri("/oauth2/token").post().go()
```
with nothing that received the `body`. I reinstalled and now it contains `body_handler()`. Fixing that, and reordering the inputs fixed the issue. Thanks!

**Comment by mooreds** [comment]
Thanks!
